
services:
  db:
    image: mongo:8.0
    # ports:
    #   - "27017:27017"
    volumes:
      - ./data/db:/data/db
  redis:
    image: redis:7.0
    # ports:
    #   - "6379:6379"
    volumes:
      - ./data/redis:/data/redis
  server:
    image: prim/phobos-auth:1.0.0
    build:
      context: "."
    restart: always
    container_name: "phobos-auth"
    ports:
      - "3200:3100"