
services:
  db:
    image: mongo:8.0
    # ports:
    #   - "27018:27017"
    restart: always
    volumes:
      - ./data/db:/data/db
      - ./docker-entrypoint-initdb.js:/docker-entrypoint-initdb.d/docker-entrypoint-initdb.js:ro
    command: --quiet
  redis:
    image: redis:7.0
    restart: always
    volumes:
      - ./data/redis:/data/redis
  server:
    image: prim/phobos-auth:1.0.0
    build:
      context: "."
    restart: always
    container_name: "phobos-auth"
    ports:
      - "${PHOBOS_AUTH_PORT:-3000}:3000"
    volumes:
      - ./logs:/logs
    depends_on:
      - db
      - redis
    secrets:
      - jwt_private_key
      - jwt_public_key
    environment:
      - MONGO_DB_HOST=db
      - REDIS_DB_HOST=redis

secrets:
  jwt_private_key:
      file: ./secrets/private_key.pem
  jwt_public_key:
      file: ./secrets/public_key.pem

    