services:
  db:
    image: mongo:8.0
    volumes:
      - ../data/db:/data/db
      - ../docker-entrypoint-initdb.js:/docker-entrypoint-initdb.d/docker-entrypoint-initdb.js:ro


  redis:
    image: redis:7.0
    volumes:
      - ../data/redis:/data/redis

  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - MONGO_DB_HOST=db
      - REDIS_DB_HOST=redis
    volumes:
      - ..:/workspace
      - /workspace/node_modules
      - /workspace/dist
      - /workspace/apps/frontend/dist
      - /workspace/apps/backend/dist
      
      # Basic git configuration forwarding
      - ~/.gitconfig:/tmp/host-gitconfig:ro
      - ~/.git-credentials:/home/node/.git-credentials:ro
      - ~/.ssh:/home/node/.ssh:ro