apiVersion: apps/v1
kind: Deployment
metadata:
  name: phobos-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phobos-auth
  template:
    metadata:
      labels:
        app: phobos-auth
    spec:
      containers:
      - name: phobos-auth
        image: "prim/phobos-auth:{{ .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_DB_HOST
          value: "redis"
        - name: MONGO_DB_HOST
          value: "db"
        - name: BASE_PATH
          value: "{{ .Values.mfe.path }}"
        volumeMounts:
        - name: jwt-volume
          mountPath: "/run/secrets/jwt"
          readOnly: true
      volumes:
      - name: jwt-volume
        secret:
          secretName: jwt-keys
          defaultMode: 256