apiVersion: v1
kind: Secret
metadata:
  name: jwt-keys
type: Opaque
data:
  jwt_private_key: {{ .Values.auth.keys.private | b64enc | quote }}
  jwt_public_key: {{ .Values.auth.keys.public | b64enc | quote }}